
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Archivo de configuración
      - redis_data:/data  # Persistencia de datos
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - coolify
    restart: unless-stopped
  
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: "contra"  # ¡Actualiza esto!
    networks:
      - coolify
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    build:
      context: 'https://github.com/miuguelt/Monitoreo.git'
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - coolify
    restart: unless-stopped

    netdata:
      image: netdata/netdata:latest
      container_name: netdata
      ports:
        - "19999:19999"  # Puerto de la interfaz web de Netdata
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /etc/os-release:/etc/os-release:ro
        - /etc/passwd:/etc/passwd:ro
        - /etc/group:/etc/group:ro
      environment:
        - NETDATA_HOSTNAME=coolify-monitor  # Nombre del host en Netdata
      restart: unless-stopped
      networks:
        - coolify_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - coolify
    restart: unless-stopped



# Nota: La configuración de Prometheus (global, scrape_configs) debe estar en el archivo prometheus.yml y no en este archivo docker-compose.yml.

volumes:
  redis_data:
  prometheus_data:
